sonar.organization=puj-course
sonar.projectKey=puj-course_FIS_2610_3517_G4

sonar.sources=apps/web/src
sonar.tests=apps/web/src
sonar.test.inclusions=apps/web/src/**/*.test.js,apps/web/src/**/*.spec.js
sonar.exclusions=apps/web/src/**/*.test.js,apps/web/src/**/*.spec.js,apps/web/coverage/**,apps/web/dist/**,apps/web/node_modules/**

sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.sourceEncoding=UTF-8
