sonar.organization=puj-course
sonar.projectKey=puj-course_FIS_2610_3517_G4

sonar.sources=apps/web/src
sonar.tests=apps/web/src
sonar.test.inclusions=apps/web/src/**/*.test.js,apps/web/src/**/*.spec.js
sonar.exclusions=apps/web/src/**/*.test.js,apps/web/src/**/*.spec.js,apps/web/coverage/**,apps/web/dist/**,apps/web/node_modules/**

sonar.coverage.exclusions=\
apps/web/src/main.jsx,\
apps/web/src/App.jsx,\
apps/web/src/Routes/**,\
apps/web/src/components/**,\
apps/web/src/pages/**,\
apps/web/src/layouts/**,\
apps/web/src/contexts/**,\
apps/web/src/patterns/factory/**,\
apps/web/src/patterns/singleton/**,\
apps/web/src/patterns/strategy/**,\
apps/web/src/services/api.js,\
apps/web/src/utils/reporteGenerator.js,\
apps/web/src/hooks/useAlertHub.js,\
apps/web/src/hooks/useAlerts.js,\
apps/web/src/hooks/useAlertsFacade.js,\
apps/web/src/hooks/useConductors.js,\
apps/web/src/hooks/useDocumentStatus.js,\
apps/web/src/hooks/useDocuments.js,\
apps/web/src/hooks/useLocalStorage.js,\
apps/web/src/hooks/useModalManager.js,\
apps/web/src/hooks/useSimulatedDate.js,\
apps/web/src/hooks/useValidationHistory.js,\
apps/web/src/hooks/useVehicles.js

sonar.cpd.exclusions=\
apps/web/src/components/**,\
apps/web/src/pages/**,\
apps/web/src/layouts/**,\
apps/web/src/contexts/**

sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.sourceEncoding=UTF-8
