name: CI - Pruebas del proyecto JS

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test --if-present

      - name: Validación final
        run: echo "Integración continua ejecutada correctamente"
